apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: ai-cost-platform
data:
  APP_ENV: "production"
  DEBUG: "false"
  APP_NAME: "AI Cost Intelligence Platform"
  APP_VERSION: "1.0.0"
  KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"
  KAFKA_GROUP_ID: "ai-cost-platform"
  OTEL_SERVICE_NAME: "ai-cost-platform-backend"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4317"
  ALLOWED_ORIGINS: '["https://app.aicostplatform.com"]'
